[build]
  command = "echo 'VITE_SUPABASE_URL:' $VITE_SUPABASE_URL && echo 'VITE_SUPABASE_ANON_KEY length:' ${#VITE_SUPABASE_ANON_KEY} && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
